# Generated by Django 4.1.3 on 2022-12-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0002_portafolio_delete_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='ips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('enrutable', models.CharField(max_length=50)),
            ],
        ),
    ]
