# Generated by Django 4.1.3 on 2022-12-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0003_ips'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ips',
        ),
    ]
