# Generated by Django 4.1.3 on 2022-12-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0006_alter_portafolio_descripcion_alter_portafolio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='autor',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
