# Generated by Django 4.1.3 on 2022-12-10 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secundario', '0008_alter_portafolio_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
