# Generated by Django 4.1.3 on 2022-12-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0009_alter_portafolio_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='etiqueta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='foto',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='url',
            field=models.URLField(),
        ),
    ]
